[window]
dimensions = { columns = 100, lines = 25 }
decorations = "None"
opacity = 0.8
padding = { x = 5, y = 5 }
dynamic_padding = false
startup_mode = "Windowed"

[font]
normal = { family = "JetBrains Mono", style = "Regular" }
bold = { family = "JetBrains Mono", style = "Bold" }
italic = { family = "JetBrains Mono", style = "Italic" }
bold_italic = { family = "JetBrains Mono", style = "Bold Italic" }
size = 12.0

[colors.primary]
background = "0x000000"
foreground = "0xffffff"

[cursor.style]
shape = "Block"
blinking = "On"

[scrolling]
history = 10000
multiplier = 3
